---
- name: Installeer nginx
  become: yes
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Configureer indexpagina
  become: yes
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'

- name: Pas nginx aan naar custom poort
  become: yes
  lineinfile:
    path: /etc/nginx/sites-available/default
    regexp: 'listen 80 default_server;'
    line: "    listen {{ nginx_port }} default_server;"
    backup: yes

- name: Nginx herstarten
  become: yes
  systemd:
    name: nginx
    state: restarted
