---
- name: Variabelen oefenen
  hosts: all
  become: true
  vars:
    motd_message: "Welkom bij het lab"
  tasks:
    - name: Zet MOTD tekst
      ansible.builtin.copy:
        dest: /etc/motd
        content: "{{ motd_message }}"

    - name: Maak app.conf met app_name uit inventory
      ansible.builtin.copy:
        dest: /etc/app.conf
        content: "Application = {{ app_name }}"

    - name: Haal kernel versie op
      ansible.builtin.command: uname -r
      register: kernel_version

    - name: Sla kernel versie op in /tmp/kernel.txt
      ansible.builtin.copy:
        dest: /tmp/kernel.txt
        content: "{{ kernel_version.stdout }}"

    - name: Sla distributienaam op in /tmp/facts.txt
      ansible.builtin.copy:
        dest: /tmp/facts.txt
        content: "{{ ansible_distribution }}"
